apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: mzzgtw33y-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:8c98575782e38315ca3f90661f7f7c7b6e19a5ca@sha256:bc2ad35fc0dfe19987c58a15ab7edcf98622e91dea07c55ae0e100b13fef86a0
          name: container-image
